name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Add Account ID to wrangler.toml"
        run: |
          touch .env
          echo account_id = \"${{ secrets.CLOUDFLARE_ACCOUNT_ID }}\" >> wrangler.toml
      - name: "Install dependencies"
        run: npm install
      - name: "Deploy to Cloudflare"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npm run deploy
