name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Add env vars to wrangler.toml"
        run: |
          echo "\n\naccount_id = \"${{ secrets.CLOUDFLARE_ACCOUNT_ID }}\"" >> wrangler.toml
          echo "\n\n[vars]" >> wrangler.toml
          echo "\nRESOURCE_NAME = \"${{ secrets.RESOURCE_NAME }}\"" >> wrangler.toml
          echo "\nDEPLOY_NAME_GPT35 = \"${{ secrets.DEPLOY_NAME_GPT35 }}\"" >> wrangler.toml
          echo "\nDEPLOY_NAME_GPT4 = \"${{ secrets.DEPLOY_NAME_GPT4 }}\"" >> wrangler.toml
          echo "\nDEPLOY_NAME_GPT4_32K = \"${{ secrets.DEPLOY_NAME_GPT4_32K }}\"" >> wrangler.toml
      - name: "Install dependencies"
        run: npm install
      - name: "Deploy to Cloudflare"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npm run deploy
